version: '3.7'
services:
  front-envoy:
    build:
      context: './front'
    networks:
      - envoymesh
    expose:
      - "80"
      - "8001"
    ports:
      - "8000:80"
      - "8001:8001" # admin

  http-backend:
    build:
      context: './http-backend'
    expose:
      - '8081'
    networks:
      envoymesh:
        # NOTE: aliases is important to round-robin even while scaling-out
        # @see https://github.com/envoyproxy/envoy/tree/master/examples/front-proxy
        aliases:
          - backend
    deploy:
      # NOTE: use version 3+ and pass `--compatibility` option
      # @see https://github.com/docker/compose/issues/5586#issuecomment-375580132
      replicas: 3

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - '9090:9090'

  grafana:
    image: grafana/grafana
    ports:
      - '3000:3000'
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
      - ./grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ./grafana/dashboard.json:/etc/grafana/provisioning/dashboards/dashboard.json

  statsd_exporter:
    image: prom/statsd-exporter:latest
    ports:
      - "9125:9125"
      - "9102:9102"

networks:
  envoymesh: {}