version: "3.7"
services:

  front-envoy:
    build:
      context: './front'
    networks:
      - envoymesh
    expose:
      - "80"
      - "8001"
    ports:
      - "8000:80"
      - "8001:8001" # admin

  service1:
    build:
      context: './service'
    networks:
      envoymesh:
        # `aliases` is important here.
        # when container get scale-out, internal DSN will respond
        # the scaled-out new container' IP.
        # @see https://christina04.hatenablog.com/entry/envoy-front-proxy
        aliases:
          - service1
    environment:
      - SERVICE_NAME=1
    expose:
      - "80"

  service2:
    build:
      context: './service'
    networks:
      envoymesh:
        aliases:
          - service2
    environment:
      - SERVICE_NAME=2
    expose:
      - "80"

  service3:
    build:
      context: './service'
    networks:
      envoymesh:
        aliases:
          - service3
    environment:
      - SERVICE_NAME=3
    expose:
      - "80"
    deploy:
      # NOTE: use version 3+ and pass `--compatibility` option
      # @see https://github.com/docker/compose/issues/5586#issuecomment-375580132
      replicas: 3

networks:
  envoymesh: {}
